"""Canonical report contract consumed by every output renderer."""

from fairlendkit.metrics.contracts import (
    CANONICAL_UNDEFINED_MESSAGES_V2,
    MetricNameV2,
    UndefinedReasonCodeV2,
)
from fairlendkit.report.models import (
    AUDIT_RESULT_SCHEMA_VERSION,
    AUDIT_RESULT_SCHEMA_VERSION_V1_0,
    AuditGroup,
    AuditResult,
    AuditResultV1_0,
    AuditResultV2,
    ExclusionRecord,
    Limitation,
    MetricName,
    MigrationProvenanceV2,
    ObservedMetric,
    PractitionerReviewNote,
    ReportedMetricValue,
    RunMetadata,
    RunMetadataV2,
    ScreeningFlag,
    StatisticalUncertainty,
    UncertaintyMethod,
    UndefinedReason,
    UndefinedReasonCode,
    ValidationEvidence,
    WarningRecord,
    to_validation_evidence,
    migrate_audit_result_v1_0,
)

__all__ = [
    "AUDIT_RESULT_SCHEMA_VERSION",
    "AUDIT_RESULT_SCHEMA_VERSION_V1_0",
    "CANONICAL_UNDEFINED_MESSAGES_V2",
    "AuditGroup",
    "AuditResult",
    "AuditResultV1_0",
    "AuditResultV2",
    "ExclusionRecord",
    "Limitation",
    "MetricName",
    "MigrationProvenanceV2",
    "MetricNameV2",
    "ObservedMetric",
    "PractitionerReviewNote",
    "ReportedMetricValue",
    "RunMetadata",
    "RunMetadataV2",
    "ScreeningFlag",
    "StatisticalUncertainty",
    "UncertaintyMethod",
    "UndefinedReason",
    "UndefinedReasonCode",
    "UndefinedReasonCodeV2",
    "ValidationEvidence",
    "WarningRecord",
    "to_validation_evidence",
    "migrate_audit_result_v1_0",
]
